### ISSUE TITLE
Missing spain_regions when following README.md

### ISSUE THREAD

**Issue by skgsergio** [ramiroaznar/covid19-geom-by-date#11]
With an empty CARTO account, you get the following error just by running the step by step detailed in the README.md:

```
Traceback (most recent call last):
  File "/home/sconde/covid19-geom-by-date/venv/lib/python3.8/site-packages/carto/sql.py", line 109, in send
    return self.auth_client.get_response_data(resp, parse_json)
  File "/home/sconde/covid19-geom-by-date/venv/lib/python3.8/site-packages/pyrestcli/auth.py", line 51, in get_response_data
    raise BaseException.create(response)
  File "/home/sconde/covid19-geom-by-date/venv/lib/python3.8/site-packages/pyrestcli/exceptions.py", line 38, in create
    raise klass(message, status_code, headers, reason, url)
pyrestcli.exceptions.BadRequestException: ['relation "spain_regions" does not exist']
```

**Comment by ramiroaznar** [comment]
Fixed! @skgsergio thanks for the heads up!
